############################
#        MONITORS
############################

monitor=,preferred,auto,auto


############################
#        SOURCES
############################

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/themes.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf



############################
#        ENVIRONMENT
############################

# Desktop session
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# Default terminal
env = TERMINAL,kitty

# Qt Platform (Wayland first, fallback to X11)
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt5ct
# env = QT_STYLE_OVERRIDE,kvantum

# Qt6 Support
env = QT6_QPA_PLATFORM,wayland
env = QT6_QPA_PLATFORMTHEME,qt6ct

# Fix for some Qt apps on Wayland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

